create table COMPLETED_CONTENT
(
    USER_ID        NUMBER not null
        constraint COMPLETED_CONTENT_USER_USER_ID_FK
            references "USER",
    CONTENT_ID     NUMBER not null
        constraint COMPLETED_CONTENT_CONTENTS_CONTENT_ID_FK
            references CONTENTS,
    OBTAINED_MARKS NUMBER not null,
    constraint COMPLETED_CONTENT_PK
        primary key (USER_ID, CONTENT_ID)
)
/

INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 1, 10);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 2, 12);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 3, 25);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 4, 10);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 5, 13);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 6, 18);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 7, 25);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 8, 16);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 9, 19);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 10, 18);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 11, 17);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 12, 12);
INSERT INTO COMPLETED_CONTENT(USER_ID, CONTENT_ID, OBTAINED_MARKS) VALUES (11, 13, 15);
