create table INDEPENDENT_INSTRUCTOR
(
    USER_ID   NUMBER not null
        constraint INDEPENDENT_PK
            primary key
        constraint INDEPENDENT_USER_USER_ID_FK
            references "USER",
    WORKPLACE VARCHAR2(50)
)
/

INSERT INTO INDEPENDENT_INSTRUCTOR (USER_ID, WORKPLACE) VALUES (1, 'Microsoft');
INSERT INTO INDEPENDENT_INSTRUCTOR (USER_ID, WORKPLACE) VALUES (3, 'Google');
INSERT INTO INDEPENDENT_INSTRUCTOR (USER_ID, WORKPLACE) VALUES (5, 'Amazon');
INSERT INTO INDEPENDENT_INSTRUCTOR (USER_ID, WORKPLACE) VALUES (8, 'DeepLearning.AI');
INSERT INTO INDEPENDENT_INSTRUCTOR (USER_ID, WORKPLACE) VALUES (9, 'Google');
