INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00002, 'C++ Programming', 4.9);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00003, 'Mathematics', 4.8);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00004, 'Law and Finance', 4.8);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00005, 'Physics', 4.9);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00006, 'College Chemistry', 4.7);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00007, 'School Chemistry', 4.6);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00008, 'Operating System, Machine Learning, AI', 4.8);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (00009, 'University Chemistry', 4.7);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (000010, 'Full Stack Web Development', 5.0);
