create table INSTRUCTS
(
    USER_ID   int not null
        constraint INSTRUCTS_USER_USER_ID_FK
            references "USER",
    COURSE_ID int not null
        constraint INSTRUCTS_COURSE_COURSE_ID_FK
            references COURSE,
    constraint INSTRUCTS_PK
        primary key (USER_ID, COURSE_ID)
)
/

INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (1, 1);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (2, 2);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (3, 6);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (10, 3);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (6, 4);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (4, 10);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (5, 7);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (7, 5);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (8, 8);
INSERT INTO INSTRUCTS (USER_ID, COURSE_ID) VALUES (9, 9);

