create table INSTITUTIONAL_INSTRUCTOR
(
    USER_ID        NUMBER not null
        constraint INSTITUTIONAL_INSTRUCTOR_PK
            primary key
        constraint INSTITUTIONAL_INSTRUCTOR_USER_USER_ID_FK
            references "USER",
    INSTITUTION_ID NUMBER not null
        constraint INSTITUTIONAL_INSTRUCTOR_INSTITUTION_INSTITUTION_ID_FK
            references INSTITUTION
)
/

INSERT INTO INSTITUTIONAL_INSTRUCTOR (USER_ID, INSTITUTION_ID) VALUES (2, 1);
INSERT INTO INSTITUTIONAL_INSTRUCTOR (USER_ID, INSTITUTION_ID) VALUES (4, 1);
INSERT INTO INSTITUTIONAL_INSTRUCTOR (USER_ID, INSTITUTION_ID) VALUES (6, 5);
INSERT INTO INSTITUTIONAL_INSTRUCTOR (USER_ID, INSTITUTION_ID) VALUES (7, 4);
INSERT INTO INSTITUTIONAL_INSTRUCTOR (USER_ID, INSTITUTION_ID) VALUES (10, 1);
