create table INSTRUCTOR
(
    USER_ID    NUMBER
        constraint INSTRUCTOR_USER__FK
            references "USER"
                on delete set null,
    SPECIALITY VARCHAR2(100),
    RATINGS    FLOAT
)
/

INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (1, 'Java Programming', 3.9);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (2, 'C++ Programming', 4.9);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (3, 'Mathematics', 4.8);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (4, 'Law and Finance', 4.8);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (5, 'Physics', 4.9);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (6, 'College Chemistry', 4.7);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (7, 'School Chemistry', 4.6);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (8, 'Operating System, Machine Learning, AI', 4.8);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (9, 'University Chemistry', 4.7);
INSERT INTO INSTRUCTOR (USER_ID, SPECIALITY, RATINGS) VALUES (10, 'Full Stack Web Development', 5.0);

