create table STUDENT
(
    USER_ID        int not null
        constraint STUDENT_USER_USER_ID_FK
            references "USER",
    EDUCATIONAL_LEVEL          VARCHAR(30),
    INSTITUTION_ID int not null
        constraint STUDENT_INSTITUTION_INSTITUTION_ID_FK
            references INSTITUTION
)
/

create unique index STUDENT_USER_ID_UINDEX
    on STUDENT (USER_ID)
/

INSERT INTO STUDENT (USER_ID, EDUCATIONAL_LEVEL, INSTITUTION_ID) VALUES (00011, 'School', 00004);
INSERT INTO STUDENT (USER_ID, EDUCATIONAL_LEVEL, INSTITUTION_ID) VALUES (00012, 'School', 00004);
INSERT INTO STUDENT (USER_ID, EDUCATIONAL_LEVEL, INSTITUTION_ID) VALUES (00013, 'College', 00005);
INSERT INTO STUDENT (USER_ID, EDUCATIONAL_LEVEL, INSTITUTION_ID) VALUES (00014, 'Undergraduate', 00001);